service: viz

runtime: custom
env: flex

automatic_scaling:
  min_num_instances: 3
  max_num_instances: 13
  cool_down_period_sec: 120 # default value
  cpu_utilization:
    target_utilization: 0.5

env_variables:
  APIROOT: '{{APIROOT}}'
  API_MODE: '{{API_MODE}}'
  NODE_PATH: '{{NODE_PATH}}'
  NODE_ENV: '{{NODE_ENV}}'